### ISSUE TITLE
left over

### ISSUE THREAD

**Issue by KazumaWada** [kazumawada/myapp#143]
### 優先順位をつけないと終わらないから注意

- [x] footerを下に固定する(下に常にstickしてると、サイトの美しさが半減すると思う。)#158
- [ ] deleteを投稿詳細に表示させる(homeはわざわざ書かなくて良い)
- [x] いいねをhomeに表示させる。#145
- [ ] ↑homeのリファクタリング #147 , 
- [x] users/showの投稿を新着順にする。#262
- [ ] 新着、人気、いいね数どのタブを今見ているか分かりやすくしたい。(hoverすると、周りが青くなるみたいな。)
- [x] 投稿数を表示する　#262
- [ ] いいねもらった数を表示する。
- [x] seedにいいねを追加する。✨#148
- [x] seedに日付を表示する。✨#148
- [x] seedにフォローフォロワーを設定する。✨#155
- [x] ↑新着順になっていなかったから、それも実装する(home)✨#148
- [x] いいねをseedで追加すると、unlikeしたときに反映されないから、一旦コメントアウト。#155 
- [x] seedに各投稿で異なる画像を設定する。✨ #155 
- [x] seedに各投稿で異なるcontentを設定する.✨ #155 
- [x] hashtag.htmlが雑だから直す。#158
- [x]  #aboutにreadmeに書く(技術の説明などを書く。)ER図, クラウドアーキテクチャー✨
- [x] ↑それの下書きをする✨
- [x] いいねの非同期化✨
- [ ] kaminariをusers/;idに実装✨ 
- [x] users/showのUIが雑だったから直す✨ #185
